/* SDES-4804 || ALTERA CONSUMOS E CALCULA RATEIO  || 0005653142 - MANSAO BENJAMIM DE CARVALHO */

DECLARE

  V_SIGLA  CHAR(20) := '';
  V_EXISTE INTEGER;
 
BEGIN
	
  SELECT SIGLA INTO V_SIGLA FROM EMPRESA WHERE ID_EMPRESA = '0001';

  IF V_SIGLA = 'DESO' THEN
  
    UPDATE CONSUMO C
       SET C.CONFAT = 1251, C.CREDITO_CONSUMO = 0, C.CREDITO_UTILIZADO = 0
     WHERE C.MATRICULA = '0005653142'
       AND C.ANO_MES_LEITURA = '202311';
  
    COMMIT;
   
    -------------------------------RECALCULO DE RATEIO-----------------------------
   
    DELETE LIGACAO_VINCULADA_CONSUMO
     WHERE MATRICULA_PAI = '0005653142'
       AND ANO_MES_LEITURA = '202311';
  
    COMMIT;
   
    P_RATEIO_FATURA('202311', '0005653142', 0, 0);
   
    COMMIT;
   
  END IF;

END;
