/*

    GERAÇÃO DE FATURAS PP - ATS
 
*/
-- 1) GERA PARA TODOS OS CENTRALIZADORES
--    INFORMAR APENAS O MÉS DE REFER?NCIA
--    NA CARGA DA VARIAVEL
DECLARE
  P_ANO_MES CHAR(6);
  P_TIPO_LOCALIDADE NUMBER;
  P_LOCALIDADE CHAR(7);
  P_ID_CENTRALIZADOR CHAR(200);
BEGIN
  P_ANO_MES := '202407';
  P_TIPO_LOCALIDADE := NULL;
  P_LOCALIDADE := NULL;
  P_ID_CENTRALIZADOR := NULL;

  P_GERA_FAT_GERAL(
    P_ANO_MES => P_ANO_MES,
    P_TIPO_LOCALIDADE => P_TIPO_LOCALIDADE,
    P_LOCALIDADE => P_LOCALIDADE,
    P_ID_CENTRALIZADOR => P_ID_CENTRALIZADOR
  );
--rollback; 
END;

-- 2) GERA APENAS PARA UM CENTRALIZADOR
--    INFORMAR APENAS O M?S DE REFER?NCIA E
--    O ID_CENTRALIZADOR NA CARGA DA VARIAVEL.
DECLARE
  P_ANO_MES CHAR(6);
  P_TIPO_LOCALIDADE NUMBER;
  P_LOCALIDADE CHAR(7);
  P_ID_CENTRALIZADOR CHAR(200);
BEGIN
  P_ANO_MES := '202407';
  P_TIPO_LOCALIDADE := NULL;
  P_LOCALIDADE := NULL;
  P_ID_CENTRALIZADOR := 2132;

  P_GERA_FAT_PUBLICO_PARTICULAR(
    P_ANO_MES => P_ANO_MES,
    P_TIPO_LOCALIDADE => P_TIPO_LOCALIDADE,
    P_LOCALIDADE => P_LOCALIDADE,
    P_ID_CENTRALIZADOR => P_ID_CENTRALIZADOR
  );
--rollback; 
END;
