SELECT CE.ID_CLIENTE_ENVIO,
CE.MATRICULA,
R.NOME_REGIAO, 
M.NOME_MUNICIPIO, 
C.ID_CENTRALIZADOR ID_CENT,
C.DESCR_CENTRALIZADOR,
CE.SEQ_ORIGINAL,
CE.ANO_MES,
CT.VL_DO_MES,
CE.DATA_INCLUSAO,
CE.DATA_ENVIO,
CE.SITUACAO_ENVIO,
TSE.DESCR_SITUACAO,
TSE.MODO,
CE.TENTATIVA,
CE.DATA_GERACAO,
CE.ARQUIVO,
CE.TIPO_ENVIO,
CE.TIPO_FATURA,
CE.NOME_ARQUIVO,
CE.EMAIL_ENVIO,
CE.DESCR_DIR 
FROM CLIENTE_ENVIO CE
JOIN TAB_SITUACAO_ENVIO TSE
ON CE.SITUACAO_ENVIO  = TSE.ID_SITUACAO_ENVIO
JOIN CLIENTE CLI
ON CE.MATRICULA = CLI.MATRICULA 
JOIN CENTRALIZADOR C 
ON CLI.ID_CENTRALIZADOR = C.ID_CENTRALIZADOR 
JOIN REGIAO R 
ON CLI.ID_REGIAO = R.ID_REGIAO 
JOIN MUNICIPIO M 
ON CLI.ID_MUNICIPIO = M.COD_MUNICIPIO 
JOIN CONTA CT 
ON CE.SEQ_ORIGINAL = CT.SEQ_ORIGINAL 
WHERE CE.ANO_MES = '202407';

SELECT COUNT (*) AS QTD_FATURAS, SITUACAO_ENVIO,
DESCR_SITUACAO  
FROM 
(SELECT CE.ID_CLIENTE_ENVIO,
CE.MATRICULA,
C.ID_CENTRALIZADOR ID_CENT,
C.DESCR_CENTRALIZADOR,
CE.SEQ_ORIGINAL,
CE.ANO_MES,
CE.DATA_INCLUSAO,
CE.DATA_ENVIO,
CE.SITUACAO_ENVIO,
TSE.DESCR_SITUACAO,
TSE.MODO,
CE.TENTATIVA,
CE.DATA_GERACAO,
CE.ARQUIVO,
CE.TIPO_ENVIO,
CE.TIPO_FATURA,
CE.NOME_ARQUIVO,
CE.EMAIL_ENVIO,
CE.DESCR_DIR 
FROM CLIENTE_ENVIO CE
JOIN TAB_SITUACAO_ENVIO TSE
ON CE.SITUACAO_ENVIO  = TSE.ID_SITUACAO_ENVIO
JOIN CLIENTE CLI
ON CE.MATRICULA = CLI.MATRICULA 
JOIN CENTRALIZADOR C 
ON CLI.ID_CENTRALIZADOR = C.ID_CENTRALIZADOR 
WHERE CE.ANO_MES = '202407')
--WHERE SITUACAO_ENVIO <> 4
GROUP BY  SITUACAO_ENVIO,
DESCR_SITUACAO  